#jdbc.driverClassName=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://127.0.0.1:3306/leyou
#jdbc.username=root
#jdbc.password=123
# 连接四大参数
#spring.datasource.url=jdbc:mysql://localhost:3306/heima
#spring.datasource.username=root
#spring.datasource.password=123
#更改映射端口
server:
  port: 80
# 设置com.kcj包的日志级别为debug org.springframework日志级别为debug
logging:
  level:
    com.kcj: debug
    #org.springframework: debug
# 设置com.kcj包的日志级别为debug
#logging.level.com.kcj=debug

#连接池HikariCP配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: 12345678
#mybatis驼峰配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#配置mapper文件映射（单表可以做一个通用mapper，不需要此配置）
  #mapper-locations: classpath:mappers/*.xml
  #别名扫描包（扫描pojo）
  type-aliases-package: com.kcj.pojo
